name: CI Semillero

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "eescovitchr/api-videojuegos"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4with:
      with:
      java-version: '17'
    - name: dependencias maven
      run: "mvn install --no-cache-dir --upgrade -r requirements.txt"
    - name: unit test mvn
      run: "mvn test"  
  
  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
